### ISSUE TITLE
Methods for converting euler angles to Vector3d returns incorrect data

### ISSUE THREAD

**Issue by Lignium** [SpongePowered/math#27]
Test code: https://gist.github.com/Lignium/7709c6c2c7e0bb6c280f5ce4f6c6191f
Output:

```
createDirectionDeg:(0.0, 0.0, 1.0)
eulerToVector:(-0.0, -1.0, 6.123233995736766E-17)
```

**Comment by Wolf480pl** [comment]
Judging by the [code][code]:
- phi is pitch, not yaw
- even then, it's not Euler angles. `phi==0` means straight up, `phi==90°` means horizontal, `phi==180°` means straight down. Assuming `z` is the up/down axis.
Looks like it works according to [the convention mathematicians use for a spherical coordinate system][spher].

IOW, the function doesn't do what you think it does.

[code]: https://github.com/SpongePowered/math/blob/master/src/main/template/float/org/spongepowered/math/vector/Vector3_E_.template#L476
[spher]: https://en.wikipedia.org/wiki/File:3D_Spherical_2.svg
